/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/
class Solution {
    public char findTheDifference(String s, String t) {
        int randomLetter=0;
        for(char c:s.toCharArray())
            randomLetter-=c;
        for(char c:t.toCharArray())
            randomLetter+=c;
        return (char) randomLetter;
    }
}
